
telegram.client:
  token: 333406361:AAHZsOAh448qjGDIX7I3llW1C3lNVTNf7Tw

spring.datasource:
  url: jdbc:postgresql://localhost/good_story
  username: good_story
  password: good_story
  testOnBorrow: true
  validationQuery: SELECT 1
  initialSize : 1
  maxIdle : 1
  maxActive : 5

server:
  port: 9090